[package]
name = "chomp-game"
version = "0.1.0"
edition = "2021"
authors = ["Yihui Tian", "yihui2@pdx.edu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prompted = "0.2.7"